# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(997, 655)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logoLabel = QtWidgets.QLabel(self.centralWidget)
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/images/Dygma_logo_color.png"))
        self.logoLabel.setObjectName("logoLabel")
        self.verticalLayout.addWidget(self.logoLabel)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.light_tab = QtWidgets.QWidget()
        self.light_tab.setObjectName("light_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.light_tab)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.light_white = QtWidgets.QPushButton(self.light_tab)
        self.light_white.setObjectName("light_white")
        self.gridLayout.addWidget(self.light_white, 3, 0, 1, 1)
        self.light_red = QtWidgets.QPushButton(self.light_tab)
        self.light_red.setObjectName("light_red")
        self.gridLayout.addWidget(self.light_red, 0, 0, 1, 1)
        self.light_blue = QtWidgets.QPushButton(self.light_tab)
        self.light_blue.setObjectName("light_blue")
        self.gridLayout.addWidget(self.light_blue, 2, 0, 1, 1)
        self.light_green = QtWidgets.QPushButton(self.light_tab)
        self.light_green.setObjectName("light_green")
        self.gridLayout.addWidget(self.light_green, 1, 0, 1, 1)
        self.light_off = QtWidgets.QPushButton(self.light_tab)
        self.light_off.setObjectName("light_off")
        self.gridLayout.addWidget(self.light_off, 4, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.light_tab, "")
        self.function_tab = QtWidgets.QWidget()
        self.function_tab.setObjectName("function_tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.function_tab)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_switch_test = QtWidgets.QPushButton(self.function_tab)
        self.button_switch_test.setObjectName("button_switch_test")
        self.horizontalLayout_2.addWidget(self.button_switch_test)
        self.tabWidget.addTab(self.function_tab, "")
        self.neuron_firmware_tab = QtWidgets.QWidget()
        self.neuron_firmware_tab.setObjectName("neuron_firmware_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.neuron_firmware_tab)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.neuron_firmware_tab)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label = QtWidgets.QLabel(self.neuron_firmware_tab)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.lineEdit_serial = QtWidgets.QLineEdit(self.neuron_firmware_tab)
        self.lineEdit_serial.setObjectName("lineEdit_serial")
        self.verticalLayout_4.addWidget(self.lineEdit_serial)
        self.firmware_filename = QtWidgets.QLabel(self.neuron_firmware_tab)
        self.firmware_filename.setObjectName("firmware_filename")
        self.verticalLayout_4.addWidget(self.firmware_filename)
        self.label_firmware_file = QtWidgets.QLabel(self.neuron_firmware_tab)
        self.label_firmware_file.setObjectName("label_firmware_file")
        self.verticalLayout_4.addWidget(self.label_firmware_file)
        self.update_firmware = QtWidgets.QPushButton(self.neuron_firmware_tab)
        self.update_firmware.setEnabled(False)
        self.update_firmware.setObjectName("update_firmware")
        self.verticalLayout_4.addWidget(self.update_firmware)
        self.firmware_cancel = QtWidgets.QPushButton(self.neuron_firmware_tab)
        self.firmware_cancel.setObjectName("firmware_cancel")
        self.verticalLayout_4.addWidget(self.firmware_cancel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.neuron_firmware_tab, "")
        self.magnet_tab = QtWidgets.QWidget()
        self.magnet_tab.setObjectName("magnet_tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.magnet_tab)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.magnet_pass = QtWidgets.QPushButton(self.magnet_tab)
        self.magnet_pass.setEnabled(False)
        self.magnet_pass.setObjectName("magnet_pass")
        self.horizontalLayout_8.addWidget(self.magnet_pass)
        self.magnet_fail = QtWidgets.QPushButton(self.magnet_tab)
        self.magnet_fail.setEnabled(False)
        self.magnet_fail.setObjectName("magnet_fail")
        self.horizontalLayout_8.addWidget(self.magnet_fail)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.magnet_joined = QtWidgets.QPushButton(self.magnet_tab)
        self.magnet_joined.setEnabled(True)
        self.magnet_joined.setObjectName("magnet_joined")
        self.gridLayout_2.addWidget(self.magnet_joined, 0, 0, 1, 1)
        self.magnet_split = QtWidgets.QPushButton(self.magnet_tab)
        self.magnet_split.setEnabled(False)
        self.magnet_split.setObjectName("magnet_split")
        self.gridLayout_2.addWidget(self.magnet_split, 1, 0, 1, 1)
        self.magnet_level = QtWidgets.QProgressBar(self.magnet_tab)
        self.magnet_level.setMinimum(500)
        self.magnet_level.setMaximum(800)
        self.magnet_level.setProperty("value", 600)
        self.magnet_level.setTextVisible(True)
        self.magnet_level.setObjectName("magnet_level")
        self.gridLayout_2.addWidget(self.magnet_level, 5, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 4, 0, 1, 1)
        self.magnet_restart = QtWidgets.QPushButton(self.magnet_tab)
        self.magnet_restart.setObjectName("magnet_restart")
        self.gridLayout_2.addWidget(self.magnet_restart, 3, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.magnet_tab, "")
        self.load_defaults_tab = QtWidgets.QWidget()
        self.load_defaults_tab.setObjectName("load_defaults_tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.load_defaults_tab)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.load_defaults_tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.load_defaults = QtWidgets.QPushButton(self.load_defaults_tab)
        self.load_defaults.setObjectName("load_defaults")
        self.gridLayout_3.addWidget(self.load_defaults, 2, 0, 1, 1)
        self.label_defaults_file = QtWidgets.QLabel(self.load_defaults_tab)
        self.label_defaults_file.setObjectName("label_defaults_file")
        self.gridLayout_3.addWidget(self.label_defaults_file, 1, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.load_defaults_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.log_messages = QtWidgets.QPlainTextEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_messages.sizePolicy().hasHeightForWidth())
        self.log_messages.setSizePolicy(sizePolicy)
        self.log_messages.setReadOnly(True)
        self.log_messages.setObjectName("log_messages")
        self.verticalLayout.addWidget(self.log_messages)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 997, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuDygma_Raise_Assembly_Tests = QtWidgets.QMenu(self.menuBar)
        self.menuDygma_Raise_Assembly_Tests.setObjectName("menuDygma_Raise_Assembly_Tests")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionCopy_log = QtWidgets.QAction(MainWindow)
        self.actionCopy_log.setObjectName("actionCopy_log")
        self.actionClear_log = QtWidgets.QAction(MainWindow)
        self.actionClear_log.setObjectName("actionClear_log")
        self.menuDygma_Raise_Assembly_Tests.addAction(self.actionCopy_log)
        self.menuDygma_Raise_Assembly_Tests.addAction(self.actionClear_log)
        self.menuBar.addAction(self.menuDygma_Raise_Assembly_Tests.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dygma Quality Test Software"))
        self.light_white.setText(_translate("MainWindow", "White"))
        self.light_red.setText(_translate("MainWindow", "Red"))
        self.light_blue.setText(_translate("MainWindow", "Blue"))
        self.light_green.setText(_translate("MainWindow", "Green"))
        self.light_off.setText(_translate("MainWindow", "Off"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.light_tab), _translate("MainWindow", "LED test"))
        self.button_switch_test.setText(_translate("MainWindow", "Switch test mode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.function_tab), _translate("MainWindow", "Function test"))
        self.label_5.setText(_translate("MainWindow", "Before flashing, put the keyboard in flashing mode: unplug cable, press escape and plug the cable. "))
        self.label.setText(_translate("MainWindow", "Write the serial number in this field (all letters after DRYS)"))
        self.firmware_filename.setText(_translate("MainWindow", "Firmware file:"))
        self.label_firmware_file.setText(_translate("MainWindow", "none"))
        self.update_firmware.setText(_translate("MainWindow", "Update Firmware"))
        self.firmware_cancel.setText(_translate("MainWindow", "cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.neuron_firmware_tab), _translate("MainWindow", "Flash Firmware"))
        self.magnet_pass.setText(_translate("MainWindow", "Pass"))
        self.magnet_fail.setText(_translate("MainWindow", "Fail"))
        self.magnet_joined.setText(_translate("MainWindow", "Press when keyboard is Joined"))
        self.magnet_split.setText(_translate("MainWindow", "Press when keyboard is Split"))
        self.magnet_level.setFormat(_translate("MainWindow", "%v"))
        self.magnet_restart.setText(_translate("MainWindow", "Restart test"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.magnet_tab), _translate("MainWindow", "Magnet Test"))
        self.label_6.setText(_translate("MainWindow", "Defaults file:"))
        self.load_defaults.setText(_translate("MainWindow", "Load Defaults (will wipe all settings)"))
        self.label_defaults_file.setText(_translate("MainWindow", "none"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.load_defaults_tab), _translate("MainWindow", "Load layout"))
        self.menuDygma_Raise_Assembly_Tests.setTitle(_translate("MainWindow", "Logs"))
        self.actionCopy_log.setText(_translate("MainWindow", "Copy log"))
        self.actionClear_log.setText(_translate("MainWindow", "Clear log"))
import image_rc
