language: python
matrix:
  include:
    - name: "Python 3.7.x on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11    # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4 # was just uppdated to 3.8 default by travis, which breaks upgrade pip
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip3 install -r combined_tests/requirements.txt
script:
    - if [ $TRAVIS_OS_NAME == "linux" ];   then pyinstaller -F combined_tests/combined_tests.py -n combined_tests_$TRAVIS_BRANCH.appimage  --add-data binaries:binaries   --add-data  languages:languages  ; fi
    - if [ $TRAVIS_OS_NAME == "windows" ]; then pyinstaller -F combined_tests/combined_tests.py -n combined_tests_$TRAVIS_BRANCH.exe       --add-data 'binaries;binaries' --add-data 'languages;languages' ; fi
    - if [ $TRAVIS_OS_NAME == "osx" ];     then pyinstaller -F combined_tests/combined_tests.py -n combined_tests_$TRAVIS_BRANCH.dmg       --add-data 'languages:languages'; fi
after_script:
  - find dist build
  - pip3 install s3cmd
  - s3cmd -v -d --recursive --access_key $ARTIFACTS_KEY --secret_key $ARTIFACTS_SECRET put dist s3://dygma-chrysalis/assembly_tests/$TRAVIS_BRANCH/ 
