language: python
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11    # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip3 install -r combined_tests/requirements.txt
  - pip3 install -r side_fw_updater/requirements.txt
script:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then pyinstaller -F combined_tests/combined_tests.py   -n combined_tests         ; fi
  - if [ $TRAVIS_OS_NAME == "linux" ]; then pyinstaller -F side_fw_updater/side_fw_updater.py -n side_fw_updater        ; fi
  - if [ $TRAVIS_OS_NAME == "win" ];   then pyinstaller -F combined_tests/combined_tests.py   -n combined_tests.exe     ; fi
  - if [ $TRAVIS_OS_NAME == "win" ];   then pyinstaller -F side_fw_updater/side_fw_updater.py -n side_fw_updater.exe    ; fi
  - if [ $TRAVIS_OS_NAME == "macos" ]; then pyinstaller -F combined_tests/combined_tests.py   -n combined_tests.dmg     ; fi
  - if [ $TRAVIS_OS_NAME == "macos" ]; then pyinstaller -F side_fw_updater/side_fw_updater.py -n side_fw_updater.dmg    ; fi
after_script:
  - find dist build
  - pip3 install s3cmd
  - s3cmd --recursive --access_key $ARTIFACTS_KEY --secret_key $ARTIFACTS_SECRET put dist s3://dygma-chrysalis/assembly_tests/ -vv
